/**
 * This class defines the type of call instructions known by the M machine as generated by the P language. 
 * Used in the code generation phase of the compiler.
 */
public enum CallType {
  read, 
  write, 
  address
};
