/**
 * This class defines the instructions  
 * Used in the code generation phase of the compiler.known by the M machine as generated by the P language.
 */
public enum FunctionType {
  stop("stop"),
  call("call"),
  read("read"),
  write("write"),
  accLoad("acc="),
  accStore("acc=>"),
  stackAccLoad("<acc="),
  accPlus("acc+"),
  accMinus("acc-"),
  minusAcc("-acc"),
  accTimes("acc*"),
  accDiv("acc/"),
  divAcc("/acc"),
  accCompare("accom"),
  br("br"),
  brEq("breq"),
  brNe("brne"),
  brLt("brlt"),
  brLe("brle"),
  brGt("brgt"),
  brGe("brge");
  
  private String value;

  private FunctionType (String value) {
    this.value = value;
  }
  
  public String getValue() {
    return value;
  }
};
