/**
 * This class defines the type and value for an operand in an instruction to be executed by the M machine as generated by the P language.
 * Used in the code generation phase of the compiler.
 */
public class Operand {
  public Datatype datatype;
  public OperandType opType;
  public Integer intValue;
  public String strValue;
  
  public Operand(Datatype datatype) {
    this.datatype = datatype;
  }

  public Operand(Datatype datatype, OperandType opType, Integer value) {
    this.datatype = datatype;
    this.opType = opType;
    this.intValue = value;
  }

  public Operand(Datatype datatype, OperandType opType, String value) {
    this.datatype = datatype;
    this.opType = opType;
    this.strValue = value;
  }
}
