/**
 * This class defines the type of operands used by the instructions of the M machine as generated by the P language. 
 * Used in the code generation phase of the compiler.
 */
public enum OperandType {
  unknown,
  stack8,
  stack16,
  constant,
  var,
  label,
  acc;
};
