/**
 * This class defines the type of operands used by the instructions of the M machine as generated by the P language. 
 * Used in the code generation phase of the compiler.
 */
public enum OperandType {
  stack,
  //TODO support 8-bit constant and variables in addition to the following two 16-bit operands.
  constant,
  var,
  label;
};
