/**
 * This class defines the type and value for an operand in an instruction to be executed by the M machine as generated by the P language.
 * Used in the code generation phase of the compiler.
 */
public class Operand {
  public OperandType opType;
  public Integer opValue;
  
  public Operand(OperandType opType, Integer opValue) {
    this.opType = opType;
    this.opValue = opValue;
  }
}
