/**
 * This class defines the type of special operands as use by selected instructions known by the M machine as generated by the P language. 
 * Used in the code generation phase of the compiler.
 */
public enum SpecialOperand {
  stack,
  unstack;
};
