/*
Copyright © 2023 Han Welmer.

This file is part of Z80Compiler.

Z80Compiler is free software: you can redistribute it and/or modify it under 
the terms of the GNU General Public License as published by the Free Software 
Foundation, either version 3 of the License, or (at your option) any later 
version.

Z80Compiler is distributed in the hope that it will be useful, but WITHOUT 
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with 
Z80Compiler. If not, see <https://www.gnu.org/licenses/>.
*/

package com.github.hanwelmer;

/**
 * This class defines the type and value for an operand in an instruction to be
 * executed by the M machine as generated by the P language. Used in the code
 * generation phase of the compiler.
 */
public class Operand {
  public OperandType opType;
  public Datatype datatype;
  public Integer intValue;
  public String strValue;
  public boolean isFinal = false;
  /*
   * opType | datatype | strValue | intValue |
   * -----------+-------------+------------+----------+ UNKNOWN | X | X | X |
   * CONSTANT | byt,integer | X | value | CONSTANT | string | string | X | STACK
   * | byt,integer | X | X | GLOBAL_VAR| byt,integer | X | address | LOCAL_VAR |
   * byt,integer | X | index | final var | byt,integer | identifier | value |
   * LABEL | byt,integer | name | address | ACC | byt,integer | X | X |
   */

  public Operand(OperandType opType) {
    this.opType = opType;
  }

  public Operand(OperandType opType, Datatype datatype) {
    this.opType = opType;
    this.datatype = datatype;
  }

  public Operand(String labelName, Integer address) {
    this.opType = OperandType.LABEL;
    this.datatype = Datatype.word;
    this.strValue = labelName;
    this.intValue = address;
  }

  public Operand(OperandType opType, Datatype datatype, String value) {
    this.opType = opType;
    this.datatype = datatype;
    this.strValue = value;
  }

  public Operand(OperandType opType, Datatype datatype, Integer value) {
    this.opType = opType;
    this.datatype = datatype;
    this.intValue = value;
  }

  public Operand(IdentifierType identifierType, Datatype datatype, int value) {
    if (identifierType == IdentifierType.CLASS_VARIABLE) {
      this.opType = OperandType.GLOBAL_VAR;
    } else if (identifierType == IdentifierType.LOCAL_VARIABLE) {
      this.opType = OperandType.LOCAL_VAR;
    } else {
      throw new RuntimeException("Internal compiler error: no OperandType for IdentifierType " + identifierType);
    }
    this.datatype = datatype;
    this.intValue = value;
  }

  public String toString() {
    String result = "operand(" + opType;
    if (datatype != null) {
      result += ", type=" + datatype;
    }
    if (strValue != null) {
      if (datatype == Datatype.string) {
        result += ", strValue=\"" + strValue + "\"";
      } else {
        result += ", strValue=" + strValue;
      }
    }
    if (intValue != null) {
      result += ", intValue=" + intValue;
    }
    result += ", final=" + isFinal;
    result += ")";
    return result;
  }
}
